using System;
using UnityEngine;
using UnityEngine.AI;
using UnityEngine.InputSystem;
using UnityEngine.Serialization;
using Inputs;
using Magic.Systems;

[RequireComponent(typeof(PlayerMovement))]

public class PlayerController : MonoBehaviour
{
    [SerializeField] private PlayerConfig m_config;
    [SerializeField] private PlayerMovement m_playerMovement;
    [SerializeField] private MouseResolver m_mouseResolver;
    [SerializeField] private MagicInputHelper m_magicInputHelper;

    private PlayerRotationCalculator m_playerRotationCalculator;

    private void OnValidate()
    {
        if (!m_playerMovement)
        {
            m_playerMovement = GetComponent<PlayerMovement>();
        }

        if (!m_mouseResolver)
        {
            m_mouseResolver = GetComponent<MouseResolver>();
        }
    }

    private void Start()
    {
        var camera = Camera.main;

        m_playerMovement.Initialize(m_config.speed, m_config.angularSpeed);
        m_playerRotationCalculator = new PlayerRotationCalculator(camera, transform);

        SetupCursor();
    }

    private void Update()
    {
        Vector3 mousePosition = Mouse.current.position.ReadValue();
        var lookPoint = m_playerRotationCalculator.Calculate(mousePosition);
        m_playerMovement.RotateTowards(lookPoint);


        if (Mouse.current.rightButton.wasPressedThisFrame)
        {
            Vector3? navPoint = m_mouseResolver.GetNavMeshPoint();
        
            if (navPoint.HasValue)
            {
                m_playerMovement.SetDestination(navPoint.Value);
            }
        }

        m_magicInputHelper.Update();
    }

    private void SetupCursor()
    {
        var texture = m_config.cursoreTexture;

        if (texture)
        {
            var hotspot = new Vector2(texture.width / 2f, texture.height / 2f);
            Cursor.SetCursor(texture, hotspot, CursorMode.Auto);
        }
    }
}
